console.log("Working")
console.log("test")
console.log("Naveen")
console.log("gopi")
console.log("Naveen")
console.log("gopi")
console.log("Naveen")
console.log("gopi")
console.log("Naveen")
console.log("gopi")
console.log("Naveen")
console.log("DNA")
console.log("Naveen")
console.log("DNA")
console.log("Naveen")
console.log("gopi")
console.log("Naveen")
console.log("gopi")
console.log("Naveen")
console.log("gopi")
console.log("Naveen")
console.log("gopi")
console.log("Naveen")
console.log("gopi")

console.log("Naveen")
console.log("Working")
console.log("test")
console.log("Naveen")
console.log("gopi")
console.log("Naveen")
console.log("gopi")
console.log("Naveen")
console.log("gopi")
console.log("Naveen")
console.log("gopi")
console.log("Naveen")
console.log("DNA")
console.log("Naveen")
console.log("DNA")
console.log("Naveen")
console.log("gopi")
console.log("Naveen")

console.log("gopi")
console.log("Naveen")
console.log("gopi")
console.log("Naveen")console.log("gopi")
console.log("Naveen")console.log("gopi")
console.log("Naveen")console.log("gopi")
console.log("Naveen")console.log("gopi")
console.log("Naveen")console.log("gopi")
console.log("Naveen")


console.log('abc')
console.log('abc')
console.log('abc')
console.log('abc')
console.log('abc')
console.log('abc')
console.log('abc')
console.log('abc')
console.log('abc')
console.log('abc')



console.log('abc')
console.log('abc')
console.log('abc')
console.log('abc')
console.log('abc')
console.log('abc')
console.log('abc')
console.log('abc')
console.log('abc')
for